name: "CI / CircleCI Workflow"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install
      working-directory: ./circleci-workflow

    - name: Run test
      run: yarn test
      working-directory: ./circleci-workflow

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install
      working-directory: ./circleci-workflow

    - name: Run test
      run: yarn build
      working-directory: ./circleci-workflow
