name: "CI / CircleCI Workflow"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
      working-directory: ./circleci-workflow

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
      working-directory: ./circleci-workflow

    - name: Check built artifact is up to date
      run: git diff --exit-code ./dist/index.js
      working-directory: ./circleci-workflow
